name: Continuous
on: [push]
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: xcodebuild build -project StormChaser/StormChaser.xcodeproj -scheme StormChaser -destination "platform=macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

